### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by johanfleury**
_Sorry for the previous PR, I fucked up between my accounts._

This commit adds French translation to the app.

I'm prone to do grammatical mistakes so a complete review by another French speaker would be appreciated.

I also don't know how to translate “Panic Trigger” in a short sentence.

### CODE REVIEW

**Comment by flocke** [comment]
Thank you for the translation! 👍 
I just pushed two new commits which add one new string for the next release, it would be nice if you could add it as well. Also you don't need to include the strings marked `translatable="false"` in your files.

**Comment by johanfleury** [comment]
I translated “Panic Trigger” to « Bouton d’urgence », but I don't know if it's really clear in French.

A friend of mine reviewed my translation and was ok with it.

**Comment by jfleury-at-ovh** [comment]
Thank you for merging this PR and for your work on this app !

**Comment by johanfleury** [comment]
Thank you for merging this PR and for your work on this app.

**Pull request merged**
